[package]
name = "test_kafka_consumer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kafka = "0.9.0"
#log = "0.4.17"
env_logger = "0.10.0"
#serde = "1.0.152"
serde_derive = "1.0.152"
#my_config = { path = "my_config" }
serde = { version = "1.0.93", features = ["derive"] }
serde_json = "1.0"
log = "0.4.17"
fs = "0.0.5"


[lib]
name = "test_kafka_consumer"
path = "src/lib.rs"
